name: Cowsql Jepsen tests - custom dispatch

on:
  workflow_dispatch:
    inputs:
      raft-repo:
        description: raft repo
        default: cowsql/raft
      raft-ref:
        description: raft branch or ref
        default: main
      cowsql-repo:
        description: cowsql repo
        default: cowsql/cowsql
      cowsql-ref:
        description: cowsql branch or ref
        default: main
      workloads:
        description: Workloads as a JSON array, e.g. [ 'append' ]
        required: true
      nemeses:
        description: Nemeses as a JSON array, e.g. [ 'pause', 'disk' ]
        required: true
      cli-opts:
        description: Jepsen cli opts, e.g. --node-targets primaries
        required: false

jobs:
  custom-dispatch:
    uses: cowsql/jepsen.ribon/.github/workflows/test-build-run.yml
    with:
      workloads: ${{ inputs.workloads }}
      nemeses: ${{ inputs.nemeses }}
      cli-opts: ${{ inputs.cli-opts }}
      jepsen-cowsql-repo: cowsql/jepsen.ribon
      jepsen-cowsql-ref: main
      raft-repo: ${{ inputs.raft-repo || 'cowsql/raft' }}
      raft-ref: ${{ inputs.raft-ref || 'main' }}
      cowsql-repo: ${{ inputs.cowsql-repo || 'cowsql/cowsql' }}
      cowsql-ref: ${{ inputs.cowsql-ref || 'main' }}
