name: Dqlite Jepsen tests - expected pass

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      raft-repo:
        description: raft repo
        default: cowsql/raft
      raft-ref:
        description: raft branch or ref
        default: master
      dqlite-repo:
        description: dqlite repo
        default: cowsql/cowsql
      dqlite-ref:
        description: dqlite branch or ref
        default: master

jobs:
  expected-pass:
    uses: ./.github/workflows/test-build-run.yml
    with:
      workloads: >
        [ 'append', 'bank', 'set' ]
      nemeses: >
        [ 'none', 'partition', 'kill', 'stop', 'disk', 'member',
          'partition,stop', 'partition,kill', 'partition,member',
          'packet,stop', 'pause', 'partition,disk', 'pause,disk' ]
      disk: >
        [ '0', '1' ]
      jepsen-dqlite-repo: ${{ github.repository }}
      jepsen-dqlite-ref: ${{ github.ref }}
      raft-repo: ${{ inputs.raft-repo || 'cowsql/raft' }}
      raft-ref: ${{ inputs.raft-ref || 'master' }}
      dqlite-repo: ${{ inputs.dqlite-repo || 'cowsql/cowsql' }}
      dqlite-ref: ${{ inputs.dqlite-ref || 'master' }}
