name: Cowsql Jepsen tests - expected pass

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      raft-repo:
        description: raft repo
        default: cowsql/raft
      raft-ref:
        description: raft branch or ref
        default: main
      cowsql-repo:
        description: cowsql repo
        default: cowsql/cowsql
      cowsql-ref:
        description: cowsql branch or ref
        default: main

jobs:
  expected-pass:
    uses: ./.github/workflows/test-build-run.yml
    with:
      workloads: >
        [ 'append', 'bank', 'set' ]
      nemeses: >
        [ 'none', 'partition', 'kill', 'stop', 'disk', 'member',
          'partition,stop', 'partition,kill', 'partition,member',
          'packet,stop', 'pause', 'partition,disk', 'pause,disk' ]
      jepsen-cowsql-repo: ${{ github.repository }}
      jepsen-cowsql-ref: ${{ github.ref }}
      raft-repo: ${{ inputs.raft-repo || 'cowsql/raft' }}
      raft-ref: ${{ inputs.raft-ref || 'main' }}
      cowsql-repo: ${{ inputs.cowsql-repo || 'cowsql/cowsql' }}
      cowsql-ref: ${{ inputs.cowsql-ref || 'main' }}
