name: Dqlite Jepsen tests - custom dispatch

on:
  workflow_dispatch:
    inputs:
      raft-repo:
        description: raft repo
        default: cowsql/raft
      raft-ref:
        description: raft branch or ref
        default: master
      dqlite-repo:
        description: dqlite repo
        default: cowsql/cowsql
      dqlite-ref:
        description: dqlite branch or ref
        default: master
      workloads:
        description: Workloads as a JSON array, e.g. [ 'append' ]
        required: true
      nemeses:
        description: Nemeses as a JSON array, e.g. [ 'pause', 'disk' ]
        required: true
      disk:
        description: "Enable or disable dqlite's disk-mode e.g. [ '0', '1 ]"
        required: true
      cli-opts:
        description: Jepsen cli opts, e.g. --node-targets primaries
        required: false

jobs:
  custom-dispatch:
    uses: cowsql/jepsen.ribon/.github/workflows/test-build-run.yml@master
    with:
      workloads: ${{ inputs.workloads }}
      nemeses: ${{ inputs.nemeses }}
      disk: ${{ inputs.disk }}
      cli-opts: ${{ inputs.cli-opts }}
      jepsen-dqlite-repo: cowsql/jepsen.ribon
      jepsen-dqlite-ref: master
      raft-repo: ${{ inputs.raft-repo || 'cowsql/raft' }}
      raft-ref: ${{ inputs.raft-ref || 'master' }}
      dqlite-repo: ${{ inputs.dqlite-repo || 'cowsql/cowsql' }}
      dqlite-ref: ${{ inputs.dqlite-ref || 'master' }}
